.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. safecash-qt test_safecash-qt
clean: FORCE
	$(MAKE) -C .. safecash-qt_clean test_safecash-qt_clean
check: FORCE
	$(MAKE) -C .. test_safecash-qt_check
safecash-qt safecash-qt.exe: FORCE
	 $(MAKE) -C .. safecash-qt
